### ISSUE TITLE
iOS 14 - Checkrain saying USB error in usb 3 safe mode and more...

### ISSUE THREAD

**Issue by StupidRepo** [foxlet/bootra1n#115]
Hi guys I am using bootrain but in usb 3 iOS 14 with untested mode on it just gets stuck in a device ready loop so I tried safe mode and then it worked but it said usb error so I swapped usb and it gave me root error so I went into super user mode and gave me ready loop again, how do I get this to work?

Also it says iOS 14.2 is untested

**Comment by StupidRepo** [comment]
Ok now I have the usbmux error

**Comment by StupidRepo** [comment]
Can someone please help?

**Comment by Goofychex** [comment]
When you have root error you need to start Checkra1n again with **sudo checkra1n** (you hold **CTRL** and then click **C** to exit the already opened Checkra1n.) 

For when you have a USB error displayed in your Checkra1n after a Jailbreak you don't need to worry about it. Because it doesn't matter much if your device booted successfully and you see **Checkra1n app** in your Home screen then you're done with the Jailbreak process. 

- If you have any further questions & problems. Feel free to reply to this message and ask me. Have a nice day/night! ☀️🌑
