### ISSUE TITLE
Suggestion: Make checkra1n a setuid binary

### ISSUE THREAD

**Issue by thejsa** [foxlet/bootra1n#12]
This would avoid the need to use sudo, making things even simpler for the user

**Comment by wrdg** [comment]
Or have the system auto login, and execute checkra1n upon login, and shutdown after checkra1n closes.

**Comment by Janneske2001** [comment]
I would not suggest the fact that it shuts down after closing checkra1n, because in my case (propably a bad tweaks thing) I have to rejailbreak in Safe Mode, after that in normal mode, maybe even twice because of a bad cable (`error -77`). Because I have experienced admin problems when I rejailbreak without restarting the program, I close checkra1n after each attempt, restart using `sudo checkra1n`, and try again. (To be honest, I haven't tried this with bootra1n, but it occurred with live-booting Ubuntu) But the automated login and automatic start sounds like music to my ears! I don't really have experience with coding, but I am already looking for a way how to make a setuid binary for Linux! If this could be realised, it would be the easiest Windows checkra1n method so far!

**Comment by Janneske2001** [comment]
Okay, so I found out (on Google/Reddit,) that this is already done by someone else. Indeed, you boot it up, auto-login, and automatically fires up checkra1n. But because I respect all of the efforts @foxlet has put into this, I don't want to share this method with you. I just think it's incorrect to do so... So unless @foxlet permits me to share this, I won't do this. Sorry...

**Comment by foxlet** [comment]
I've considered implementing it when the next checkra1n release is out.

**Comment by Janneske2001** [comment]
> I've considered implementing it when the next checkra1n release is out (to prevent confusion from older guides).

I am afraid that with the next version there will also be a Windows version. Maybe you can already implement it now, to see how it goes, and _if_ the next release of checkra1n still isn't for Windows, you can easily (well I don't know if it's _that_ easy) swap one checkra1n version for the other so that the transition is way faster.
But still, huge thanks for already making this possible! I don't know how to code, but luckily for me, there is the internet to find others that can!

**Comment by BananaManCJ** [comment]
Checkn1x does this, by the way

**Comment by foxlet** [comment]
Today's bootra1n release has setuid enabled. Try it out!
