### ISSUE TITLE
since my home button is broken...

### ISSUE THREAD

**Issue by patttykim** [foxlet/bootra1n#14]
Is there anyway that I can boot this program as pre-dfu moded status or no home button being required pls help me

**Comment by Janneske2001** [comment]
I know that another tool, also live-booting-checkra1n, had this (bug/feature) in the first release. This meant that with that tool, your iPhone already had to be connected in DFU-mode to start with. As this is not possible with bootra1n, I have to send you a personal message with the name of the tool, as I don't want to share the name of another, similar tool on the site of bootra1n. I just messaged the developer, because he released two versions, and only the first version supported this. Unfortunately, this version isn't on the "official" release site, only on malicious or vague websites... I hope he will soon react, so I can mail you or something.

Kind regards
Jannes

**Comment by Janneske2001** [comment]
Aargh alright, @patttykim , the tool is [checkn1x](https://www.reddit.com/r/jailbreak/comments/f0jnp8/release_checkn1x_a_20mb_linux_iso_to_jailbreak_ios/), you have to flash it on a USB-key with Etcher or Rufus, boot from it, and close the fancy checkra1n window you will directly get on your screen. Then you have to type: `checkra1n -c`. This will allow devices that are already in DFU-mode, so you can first get your iPhone into DFU mode, just google "DFU-mode iPhone ?? no home button" and connect your DFU-mode iPhone on your PC. It will automatically start jailbreaking as soon as it recognises your DFU-device. I recommend first having your device in DFU-mode, as it's possible that you will need your computer for that. Also, remember to remove your passcode, FaceID, TouchID from your iPhone before starting. Otherwise, you may encounter a -77 error.
